name: example
description: Charts-Flutter Demo
environment:
  sdk: '>=1.23.0 <3.0.0'
dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.7.0
  intl: ^0.17.0
flutter:
  uses-material-design: true
