name: charts_flutter
version: 0.11.1
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  charts_common: ^0.12.0
  # charts_common:
  #   path: ../charts_common/
  collection: ^1.15.0
  flutter:
    sdk: flutter
  intl: ^0.17.0
  logging: ^1.0.2
  meta: ^1.7.0


dev_dependencies:
  mockito: ^5.0.17
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  test: ^1.17.12
